# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02f043af2f590faeef025d1452c3075c6999af4162af374fe3d542ac6734268a0d1e0672b3d27e974383b52b03bd29a49c4eb9eceab652fb1c890b95fda83482

test:
  secret_key_base: 13905a28e47b150933fc96c0aab914d51b11cf711dfdd041449ff6191a4f254cc331bb48e6a1041ea0f709b49835a314f912d1daf29b52925f444ff0886287cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
